/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppBlog {}
  interface AppHome {}
  interface AppRoot {}
  interface SameerHeader {}
}

declare global {


  interface HTMLAppBlogElement extends Components.AppBlog, HTMLStencilElement {}
  var HTMLAppBlogElement: {
    prototype: HTMLAppBlogElement;
    new (): HTMLAppBlogElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLSameerHeaderElement extends Components.SameerHeader, HTMLStencilElement {}
  var HTMLSameerHeaderElement: {
    prototype: HTMLSameerHeaderElement;
    new (): HTMLSameerHeaderElement;
  };
  interface HTMLElementTagNameMap {
    'app-blog': HTMLAppBlogElement;
    'app-home': HTMLAppHomeElement;
    'app-root': HTMLAppRootElement;
    'sameer-header': HTMLSameerHeaderElement;
  }
}

declare namespace LocalJSX {
  interface AppBlog {}
  interface AppHome {}
  interface AppRoot {}
  interface SameerHeader {}

  interface IntrinsicElements {
    'app-blog': AppBlog;
    'app-home': AppHome;
    'app-root': AppRoot;
    'sameer-header': SameerHeader;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-blog': LocalJSX.AppBlog & JSXBase.HTMLAttributes<HTMLAppBlogElement>;
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'sameer-header': LocalJSX.SameerHeader & JSXBase.HTMLAttributes<HTMLSameerHeaderElement>;
    }
  }
}


